const mockStatementResult = [
    [
        "æ‘‡»…! ·∫Ëß™”√–¬Õ¥‡√’¬°‡°Á∫‰¥Èπ“π∂÷ß 36 ‡¥◊Õπ",
        "·∫Ëß™”√–À√◊Õ Õ∫∂“¡√“¬≈–‡Õ’¬¥‚∑√ 02-232-4288",
        "À√◊Õ«‘∏’°“√·∫Ëß™”√–™ËÕß∑“ßÕÕπ‰≈πÏ∑’Ë citi.asia/THconvertonline",
        "¢ÈÕ§«√√–«—ß!!",
        ". §«√√—°…“√À— ‡ªÁπ§«“¡≈—∫ °√≥’∫—μ√À“¬„ÀÈ√’∫·®ÈßÕ“¬—¥ ‡π◊ËÕß®“°∑Ë“πμÈÕß√—∫º‘¥™Õ∫¬Õ¥„™È®Ë“¬°ËÕπ·®ÈßÕ“¬—¥",
        ". À“°®Ë“¬‰¡Ë§√∫À√◊Õ®Ë“¬™È“ ®–∂Ÿ°‡√’¬°‡°Á∫¥Õ°‡∫’È¬·≈–§Ë“∏√√¡‡π’¬¡",
        "JIRAYU NAJA",
        "‡≈¢∑’Ë 6/610",
        "§Õπ‚¥≈ÿ¡æ‘π’æ“√Ï§‡æ™√‡°…¡ 98 Õ“§“√∫’",
        "∂ππ‡æ™√‡°…¡´Õ¬ 98",
        "·¢«ß∫“ß·§‡Àπ◊Õ",
        "‡¢μ∫“ß·§ 10160",
        "000986",
        "XXXX-XXXX-XXXX-XXXX",
        "17 SEP 23",
        "211,000",
        "02 OCT 23",
        "17,623.49",
        "27,077.25",
        "17,623.49",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "*",
        "PREVIOUS BALANCE",
        "22,703.40",
        "202",
        "0",
        "0",
        "200",
        "30",
        "22,703.40-",
        "04 SEP",
        "03 SEP",
        "PAYMENT PROMPTPAY",
        "4543-25XX-XXXX-5916",
        "JIRAYU NAJA",
        "200.00-",
        "18 AUG",
        "17 AUG",
        "MONTHLY CASH BACK CREDITED",
        "SUB-TOTAL",
        "200.00-",
        "XXXX-XXXX-XXXX-XXXX",
        "JIRAYU NAJA",
        "186.00",
        "21 AUG",
        "20 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "190.00",
        "21 AUG",
        "20 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "352.00-",
        "21 AUG",
        "21 AUG",
        "Cash Back Privileges(10%, 5%)-JUL23",
        "241.00",
        "22 AUG",
        "21 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "67.00",
        "24 AUG",
        "23 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "108.00",
        "24 AUG",
        "23 AUG",
        "MRT-BEM",
        "Bangkok",
        "TH",
        "238.00",
        "25 AUG",
        "24 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "115.00",
        "25 AUG",
        "24 AUG",
        "MRT-BEM",
        "Bangkok",
        "TH",
        "Statement",
        "of Citi Cash",
        "Back",
        "Platinum",
        "„∫·®Èß¬Õ¥∫—≠™’∫—μ√‡§√¥‘μ´‘μ’È",
        "·§™·∫Á° ·æ≈μμ‘π—Ë¡",
        "5462-v46.0",
        "Page 1/4"
    ],
    [
        "305.00",
        "28 AUG",
        "25 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "186.00",
        "28 AUG",
        "26 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "146.00",
        "29 AUG",
        "28 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "267.00",
        "31 AUG",
        "30 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "134.00",
        "01 SEP",
        "31 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "473.00",
        "01 SEP",
        "31 AUG",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "65.00",
        "04 SEP",
        "01 SEP",
        "Google YouTube",
        "650-2530000 US",
        "308.00",
        "04 SEP",
        "01 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "362.00",
        "04 SEP",
        "01 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "1,666.25",
        "04 SEP",
        "02 SEP",
        "MAKRO",
        "SANAMBIN NAM TH",
        "2,700.00",
        "07 SEP",
        "06 SEP",
        "2C2P*THAILIONAIR",
        "BANGKOK",
        "TH",
        "220.00",
        "07 SEP",
        "06 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "377.00",
        "07 SEP",
        "06 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "422.00",
        "07 SEP",
        "06 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "54.00",
        "07 SEP",
        "06 SEP",
        "MRT-BEM",
        "Bangkok",
        "TH",
        "107.00",
        "12 SEP",
        "11 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "249.00",
        "14 SEP",
        "13 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "295.00",
        "14 SEP",
        "13 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "108.00",
        "14 SEP",
        "13 SEP",
        "MRT-BEM",
        "Bangkok",
        "TH",
        "241.00",
        "15 SEP",
        "14 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "271.00",
        "15 SEP",
        "14 SEP",
        "WWW.GRAB.COM",
        "BANGKOK",
        "TH",
        "6,049.00",
        "15 SEP",
        "15 SEP",
        "2C2P (THAILAND) CO.,LTD.A(010:010)",
        "TH",
        "11,479.00",
        "15 SEP",
        "15 SEP",
        "2C2P (THAILAND) CO.,LTD.A(008:010)",
        "TH",
        "SUB-TOTAL",
        "27,277.25",
        "TOTAL",
        "27,077.25",
        "Total accounts / √«¡∑ÿ°∫—≠™’",
        "211,000",
        "27,077.25",
        "XXXX-XXXX-XXXX-XXXX",
        "211,000",
        "211,000",
        "27,077.25",
        "Total overlimit amount / ¬Õ¥‡ß‘π‡°‘π«ß‡ß‘π*",
        "0.00",
        "*°√ÿ≥“™”√–¬Õ¥‡ß‘π‡°‘π«ß‡ß‘π‡æ‘Ë¡‡μ‘¡®“°¬Õ¥‡ß‘π¢—ÈπμË”∑’ËμÈÕß™”√–∑—ÈßÀ¡¥ ºË“π∫—≠™’∫—μ√‡§√¥‘μ´‘μ’È„∫„¥„∫Àπ÷Ëß¢Õß∑Ë“π ‡æ◊ËÕ°“√„™È®Ë“¬ºË“π∫—μ√œ ‰¥ÈÕ¬Ë“ßμËÕ‡π◊ËÕß ®”π«π‡ß‘π",
        "∑’Ë‡°‘π«ß‡ß‘π ‘π‡™◊ËÕ‡ªÁπ¬Õ¥√«¡®“°∫—μ√‡§√¥‘μ´‘μ’È∑—ÈßÀ¡¥",
        "*Pleasesettle the overlimit amount in addition to the total minimum payment due amount through any of your Citi Credit Cards to continue using the card. The over limit",
        "amount is combined from all Citi Credit cards.",
        "**«ß‡ß‘π‡∫‘°‡ß‘π ¥¢Õß∫—≠™’∫—μ√œ π—ÈπÊ ‚¥¬ª√–«—μ‘°“√™”√–‡ß‘π¢Õß∑Ë“π®–¡’º≈μËÕ°“√°”Àπ¥«ß‡ß‘π‡∫‘°‡ß‘π ¥",
        "**The cash limit of other accounts will be displayed on the statement of those account, your cash limit is reflected from your payment.",
        "Statement",
        "of Citi Cash",
        "Back",
        "Platinum",
        "„∫·®Èß¬Õ¥∫—≠™’∫—μ√‡§√¥‘μ´‘μ’È",
        "·§™·∫Á° ·æ≈μμ‘π—Ë¡",
        "JIRAYU NAJA",
        "XXXX-XXXX-XXXX-XXXX",
        "5463-v46.0",
        "Page 2/4"
    ],
    [
        "CARDMEMBER'S BENEFIT & INFORMATION",
        "JIRAYU NAJA",
        "XXXX-XXXX-XXXX-XXXX",
        "5464-v46.0",
        "Page 3/4"
    ],
    [
        "000986",
        "XXXX-XXXX-XXXX-XXXX",
        "JIRAYU NAJA",
        "JIRAYU NAJA",
        "XXXX-XXXX-XXXX-XXXX",
        "5465-v46.0",
        "Page 4",
        "EBDAAOAIMFEFEFFEKAABNEFFAFJAHBAMIBJEIAMMIAAIMAIGAGIJAFEFFBCFIECACGMACIAMMIAMIAAMIBIFBANZ",
        "EBDAAOAIMFEFEFFEKAABNEFFAFJAHBAMIBJEIAMMIAAIMAIGAGIJAFEFFBCFIECACGMACIAMMIAMIAAMIBIFBANZ",
        "EBDAAOAIMFEFEFFEKAABNEFFAFJAHBAMIBJEIAMMIAAIMAIGAGIJAFEFFBCFIECACGMACIAMMIAMIAAMIBIFBANZ",
        "|010052800012701",
        "454325XXXXXX3397",
        "0",
        "/4"
    ]
];